### ISSUE TITLE
Input from list of files

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/frog#10]
I often need to run frog over thousands of files. Hence I want to run several frogs. As it is, I need to distribute the inputfiles over so many directories. I would like to just split a list of files with full pathnames and start each of the n instances of frog with a 1/n part of the list.

**Comment by kosloot** [comment]
Well, this would mean an extra level of treading complexity in Frog.
A direct and more down to earth solution is to use the wild-card possibility of the Frog command line, not using -t but just a pattern.
Assuming you have filenames with enough distinctive marks you could for instance do:
Frog <options> file1* &
Frog <options> file2* &
Frog <options> file3* &
etc.

**Comment by proycon** [comment]
Makes sense yeah...or solve it on the pipeline level (LuigiNLP), provided I fix LanguageMachines/LuigiNLP#4

**Comment by kosloot** [comment]
Or when a wild card is impossible because of too many files, use **xargs**
Example:
`find *  -type f -name "*.folia.xml*" -print0 |xargs -0 -r -I file frog  -x file`

To run on 8 files in parallel:
`find *  -type f -name "*.folia.xml*" -print0 |xargs -n1 -P8 -0 -r -I file frog  -x file`
