### ISSUE TITLE
released frog (0.29) depends on unreleased libfolia (2.15)

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/frog#101]
libfolia should probably be released for the frog release to work, now the release is broken because of this missing dependency.

**Comment by kosloot** [comment]
A, OK. In fact it will work with older versions. But the (seldom used) word-corrections feature will fail.
I will soon release a new libfolia, and then a new frog too, with fixes for memory leaks

**Comment by kosloot** [comment]
solved
