### ISSUE TITLE
Building on Ubuntu 22.04 LTS Pop!_OS

### ISSUE THREAD

**Issue by PanderMusubi** [LanguageMachines/frog#102]
The question is if the following information below is correct. I'm very new to using frog. Probably no need to add this all to the documentation, but good for those who find themselves in a similar situation.

Pop!_OS is currently still on Ubuntu 22.04 LTS. As libticcutils-dev is still at 0.24, only frog 0.21 can be built on these systems. If you desire to do so, these are the commands:

    sudo su
    apt-get -y install libexttextcat-dev libticcutils-dev libtimbl-dev libmbt-dev libfolia-dev libucto-dev frogdata
    cd /opt
    wget https://github.com/LanguageMachines/frog/releases/download/v0.21/frog-0.21.tar.gz
    tar xf frog-0.21.tar.gz
    cd frog-0.21
    bash bootstrap.sh
    autoupdate
    ./configure
    make
    make install
    exit

If you want to deinstall your build of frog first, do that with:

    sudo su
    cd /opt/frog-0.21
    make uninstall
    apt-get purge libexttextcat-dev libticcutils-dev libtimbl-dev libmbt-dev libfolia-dev libucto-dev frogdata
    apt-get autoremove
    exit

Perhaps also do this:

    rm -rf ~/.config/frog/ ~/.config/ucto/

**Comment by proycon** [comment]
The packages in debian/ubuntu are indeed quite outdated. But that doesn't mean you need to resort to an older version of Frog. A script is provided to compile all the necessary dependencies:

```
$ sudo apt-get install libxml2-dev libicu-dev libexttextcat-dev autoconf autoconf-archive automake libtool gcc
$ ./build-deps.sh          #this will build and install ticcutils, libfolia, ucto, timbl, mbt
$ bash bootstrap.sh
$ ./configure
$ make
$ make install
```

Alternatively, OCI/docker containers are available.
