### ISSUE TITLE
No Homebrew package

### ISSUE THREAD

**Issue by sanmai-NL** [LanguageMachines/frog#104]
https://languagemachines.github.io/frog/ says a macOS Homebrew package should be available. I couldn't find one.

**Comment by proycon** [comment]
Did you do `brew tap fbkarsdorp/homebrew-lamachine` ?  It's not in the main collection but in a separate *tap* you need to activate.

**Comment by sanmai-NL** [comment]
No, I wasn't aware of the tap.
