### ISSUE TITLE
[idea] Integrate semantic role labelling in Frog

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/frog#12]
The VU worked on a timbl-based semantic role labeler for Dutch. I think it would be an interesting idea to integrate this in Frog. See https://github.com/newsreader/vua-srl-nl

**Comment by proycon** [comment]
This is less obvious than I assumed. They base themselves on constituency and dependency information (alpino output), we don't have the former and the quality of the latter is too poor.

**Comment by kosloot** [comment]
close because unrealistic
