### ISSUE TITLE
Language dependent frogging of FoLiA documents

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/frog#14]
Frog should be able to detect Language information in FoLiA  and only handle sentences which are in de current language.

**Comment by kosloot** [comment]
This can be quite cumbersome. 
- Lang information in FoLiA is not always available at the level of the text. Can be meta info and or only at the paragraph level.
- You would like to be able to do this for plain text too.
Maybe it is better to build language detection into Frog itself. 
@proycon @antalvdb : opinions?

**Comment by proycon** [comment]
The lang annotation should be looked for in every structural ancestor of a particular sentence, as well as the sentence itself. Looking in document metadata would be a good fallback, although the metadata field is not strictly prescribed, but looking for 'language' in the native metadata scheme is probably a good guess.

Building language detection into Frog sounds interesting too, though that would introduce a new 3rd party dependency I guess? (langcat)

**Comment by kosloot** [comment]
That "should be looked for in every structural ancestor of a particular sentence, as well as the sentence itself." is what i call 'cumbersome'. :).

Adding a dependency on libtextcat (or one of its other incarnations)is cumbersome too. But it might be worthwhile. 
Language detection should be an option on the Frog command line anyway.

**Comment by kosloot** [comment]
Whatever is implemented, frog should ALSO be able to handle FoLiA with embedded language information.
So better start with that.
Best solution seems to have a generic function in libfolia (and folia.py) that for a TextContent searches upward for lang information.

**Comment by antalvdb** [comment]
There seems to be a 'passive' side to this issue and an 'active' side. The function that searches upwards may find nothing and therefore do nothing; if it finds language info and it is not 'nl', it does not process the text under that label. 

An active version of this function tries to classify each text segment (from the sentence up?) and will refuse to tag the sentence -- unless perhaps the user explicitly instructs Frog to ignore language information (which would be another commandline option). This would be an active component of Frog and not be part of preprocessing - it would leave language information in the FoLiA xml afterwards.

I think I only repeated what you said earlier, but to draw practical consequences, I there are sufficiently many reasons to do both.

**Comment by kosloot** [comment]
Yeah right. We probably mean the same thing. But there are a lot of issues here.
Even with FoLiA input, Frog uses Ucto to tokenize sentences/paragraphs. 
If you explicitly specify a language in Frog, you might also want to skip tokenization of other languages. 
So also Ucto needs languages awareness when processing FoLiA. 
Ucto might even tokenize sentences in different languages!
And a future Frog might then also tag/lemmatize etc in that Language!
To start, I suggest doing this:
- Don't break existing usage
- give Frog a --language option which just says: When there is language information available on a textpart, and it DOESN'T match. skip that textpart.
- -  this also implies that missing language info sticks to 'old' behavior
- - it also means that Ucto does the same: when a lang parameters is passed, ignore other languages.

In a later stage, ucto could just use any language information to tokenize using the language at hand, and frog could just apply any available tool for that language (probably just lemma and tagging)

**Comment by kosloot** [comment]
see also #15

**Comment by kosloot** [comment]
ucto now is language aware and frog uses this.
The code is tested, but now warranty as usual
