### ISSUE TITLE
Decide on one  encoding scheme for language

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/frog#15]
To keep everything under control, all FoLiA and FoLiA related tools should use the same encoding for language parameters.
IMNHO only [ ISO 692-2 ](https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes) is applicable.

Even then some issues like 'nld' versus 'dut' remain.
@proycon @martinreynaert

**Comment by proycon** [comment]
Don't use iso-639-2, use iso-639-3 instead then (three letter codes for tons of languages), dutch is ``nld``. Ucto currenctly uses iso-639-1 though (two letter codes, more limited). We can also simply use iso-639-1 for Frog and fall back to iso-639-3 only for the more exotic languages.

**Comment by kosloot** [comment]
ok, so ISO 693-3 looks the best choice in the long run.
This means some changes in existing code, an probably some hackery to be backward compatible.
This affects mainly ucto and uctodata, maybe FoLiA-langcat too
The language option in Frog is in development and can be ISO 396-3 from the start.

**Comment by kosloot** [comment]
ISO 693-3 it will be.
