### ISSUE TITLE
Frog gives seg fault when 1st line is empty

### ISSUE THREAD

**Issue by Irishx** [LanguageMachines/frog#16]
minor unimportanti issue

**Comment by kosloot** [comment]
cannot reproduce.
Please provide example input file and the command line

**Comment by kosloot** [comment]
Iris answered:
(lamachine)ihendrickx@scootaloo:/vol/tensusers/ihendrickx/Data/Ancient-greek/HDT/Frog/10cv_aug2016/Train9$ frog -n -c frog.cfg.template -t test9_metsegfault -o blub

Where blub is an empty file

**Comment by kosloot** [comment]
Ok, so it has nothing to do with blub being empty!
blub is the output file.
The problem is with 'test9_metsegfault'
And THAT is reproducible.
So I will look into that

**Comment by kosloot** [comment]
nailing it down to the combination of the -n option and an empty line, and it is an Ucto problem then. 
==>
https://github.com/LanguageMachines/ucto/issues/11

**Comment by kosloot** [comment]
Solved in ucto
