### ISSUE TITLE
CGN or D-coi part-of-speech tag set

### ISSUE THREAD

**Issue by gzuidhof** [LanguageMachines/frog#2]
Hello,

On the main page it states that the following information is present in the Frog output: 
```PoS tag (CGN tagset; according to MBT)```

After investigating output and the types in this tag set, I found that it does not contain the types `SPEC(afkorting)` and `SPEC(symbool)`. These are present in the *D-coi* tag set (the only addition I believe). 

This leads me to believe Frog tags according to the *D-coi* tag set instead of the *CGN* tag set. Am I right about this?

Kind regards,
Guido

**Comment by kosloot** [comment]
Hai Guido,

You are correct. Frog follows the D-coi standard, which includes CGN

There are some small notational differences: 
*Frog* uses ```SPEC(afk) , SPEC(afgebr)``` and ```SPEC(symb)```

*D-COI*  may use: ```SPEC(afkorting), SPEC(afgebroken)``` and ```SPEC(symbool) ```
I don't have a conclusive document at hand to check this.

Hope this answers your question, and thanks for pointing this out.

Kind Regard
Ko van der Sloot
