### ISSUE TITLE
repition of inlections in long output

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/frog#25]
Soms worden inflectie namen gedupliceerd:
[[ga]verb[t]/present-tense/singular/2nd-person-verb/present-tense/singular/2nd-person-verb]verb

dit moet zijn:
[[ga]verb[t]/present-tense/singular/2nd-person-verb]verb

Input zin: 'Het gaat om hunebedden.'

Maar er zijn ergere problemen:
de alternative lezing is:

[[ga]verb[t]/present-tense/singular/3rd-person-verb/present-tense/singular/2nd-person-verb/inver
sed]

Een tegenspraak !? Moet denk ik verworpen worden...

**Comment by kosloot** [comment]
de regel in mbm-merged is:
gaat V 0 0|te2+Ia|te3+Ia 0/te1|0/te2|0/te2I|0/te3|0

Opgesplitst in 5 regels:
gaat V 0 0 0/te1
gaat V 0 te2+Ia 0/te2
gaat V 0 te3+Ia 0/te2I
gaat V 0 te3+Ia 0/te3
gaat V 0 te3+Ia 0

In de derde variant zit de tegenspraak
Welke kan er weg???

**Comment by antalvdb** [comment]
Hi Ko,

> de regel in mbm-merged is:
> gaat V 0 0|te2+Ia|te3+Ia 0/te1|0/te2|0/te2I|0/te3|0
> 
> Opgesplitst in 5 regels:
> gaat V 0 0 0/te1
> gaat V 0 te2+Ia 0/te2
> gaat V 0 te3+Ia 0/te2I
> gaat V 0 te3+Ia 0/te3
> gaat V 0 te3+Ia 0
> 
> In de derde variant zit de tegenspraak
> Welke kan er weg???

de gaat V 0 te3+Ia 0/te2I regel klopt niet; zo’n te2I code staat voor de ‘inverse’ gevallen waar het persoonlijk voornaamwoord na het werkwoord staat, zonder -t. Dus “ga je”. Bovendien: te3 en te2 zouden niet samen moeten voorkomen. Dit komt van een foute analyse af misschien.

Het is misschien interessant om eens te zoeken op te2I in CELEX en te zien of er inconsistenties zijn te vinden.

De “0/“ in alle codes is eigenlijk niet correct, want het is wel degelijk de t die in z’n eentje een inflectie is. Eigenlijk zou er moeten staan 

Maar wacht: is het lemma bij werkwoorden niet altijd de infinitief, dus “gaan”? Hoe is dit bij “doen”?

Zucht...

  Antal

--
Antal van den Bosch http://antalvandenbosch.ruhosting.nl
Center for Language Studies, Radboud University

**Comment by kosloot** [comment]
Ha Antal,

On 12/22/2016 03:08 PM, Antal van den Bosch wrote:
> Hi Ko,
> 
>> de regel in mbm-merged is:
>> gaat V 0 0|te2+Ia|te3+Ia 0/te1|0/te2|0/te2I|0/te3|0
>>
>> Opgesplitst in 5 regels:
>> gaat V 0 0 0/te1
>> gaat V 0 te2+Ia 0/te2
>> gaat V 0 te3+Ia 0/te2I
>> gaat V 0 te3+Ia 0/te3
>> gaat V 0 te3+Ia 0
>>
>> In de derde variant zit de tegenspraak
>> Welke kan er weg???
> 
> de gaat V 0 te3+Ia 0/te2I regel klopt niet; zo’n te2I code staat voor de
> ‘inverse’ gevallen waar het persoonlijk voornaamwoord na het werkwoord
> staat, zonder -t. Dus “ga je”. Bovendien: te3 en te2 zouden niet samen
> moeten voorkomen. Dit komt van een foute analyse af misschien.

Dat dacht ik ook ja.

> Het is misschien interessant om eens te zoeken op te2I in CELEX en te
> zien of er inconsistenties zijn te vinden.
> 
> De “0/“ in alle codes is eigenlijk niet correct, want het is wel
> degelijk de t die in z’n eentje een inflectie is. Eigenlijk zou er
> moeten staan
> 
> Maar wacht: is het lemma bij werkwoorden niet altijd de infinitief, dus
> “gaan”? Hoe is dit bij “doen”?

Ik geloof (vrees) niet dat dit consequent goed gedaan is, maar:
doet V 0 0 te2|te3
moet N|V 0 0 0/e|0/te1|0/te2|0/te2I|0/te3

DUS:
Processing... 'gaat hij mee?'
1	gaat	gaan	[ga][t]	WW(pv,tgw,met-t)

Processing... 'moet hij mee?'
1	moet	moeten	[moet]	WW(pv,tgw,ev)	

Processing... 'doet hij mee?'
1	doet	doen	[doe][t	WW(pv,tgw,met-t)

Processing... 'wilt u  mee?'
1	wilt	willen	[wil][t]	WW(pv,tgw,met-t)

Processing... 'slaapt hij?'
1	slaapt	slapen	[slaap][t]	WW(pv,tgw,met-t)	

Dus NEE, blijkbaar

Fijne kerst (er er zijn nog meer MBMA issues :P

Ko

**Comment by kosloot** [comment]
Ok,

graag wat verduidelijking nog:

> Opgesplitst in 5 regels:
> > gaat V 0 0 0/te1
> > gaat V 0 te2+Ia 0/te2
> > gaat V 0 te3+Ia 0/te2I
> > gaat V 0 te3+Ia 0/te3
> > gaat V 0 te3+Ia 0
> >
> > In de derde variant zit de tegenspraak
> > Welke kan er weg???
>
> de gaat V 0 te3+Ia 0/te2I regel klopt niet; zo’n te2I code staat voor
> de ‘inverse’ gevallen waar het persoonlijk voornaamwoord na het
> werkwoord staat, zonder -t. Dus “ga je”. Bovendien: te3 en te2 zouden
> niet samen moeten voorkomen. Dit komt van een foute analyse af misschien.

Dit leidt tot de volgende 5 analyses:
gaat==> [ [gaat]V te1 ]V V
gaat==> [ [ga]V [t]te2 te2 ]V V
gaat==> [ [ga]V [t]te3 te2I ]V V
gaat==> [ [ga]V [t]te3 te3 ]V V
gaat==> [ [ga]V [t]te3 ]V V

Die derde kan dus weg.
Maar in de 2-de en 4-de zit, lijk mij redundante informatie, die in de
5-de dan weer niet zit.
> Het is misschien interessant om eens te zoeken op te2I in CELEX en te
> zien of er inconsistenties zijn te vinden.
Er zijn bijna 600 entries in mbma-merged waarbij het woord eindigt op
een 't' en die te2I hebben
zo op het oog is het alleen bij 'gaat' fout

>
> De “0/“ in alle codes is eigenlijk niet correct, want het is wel
> degelijk de t die in z’n eentje een inflectie is. Eigenlijk zou er
> moeten staan

Wat? ??
Dit werkt:
gaat V 0 0 0/te1
gaat V 0 te2+Ia 0
gaat V 0 te3+Ia 0

resultaat:
gaat==> [ [gaat]V te1 ]V V
gaat==> [ [ga]V [t]te2 ]V V
gaat==> [ [ga]V [t]te3 ]V V

Maar dit wekt ook:
gaat V 0 0 0/te1
gaat V 0 0+Ia te2
gaat V 0 0+Ia te3

geeft hetzelfde:
gaat==> [ [gaat]V te1 ]V V
gaat==> [ [ga]V [t]te2 ]V V
gaat==> [ [ga]V [t]te3 ]V V

Net als:
gaat V 0 0 0/te1
gaat V 0+Ia 0 te2
gaat V 0+Ia 0 te3

Wat is conceptueel beter? Inflecties zoveel mogelijk achteraan lijkt me
het meest logisch
De laatste oplossing dus?

Ko

**Comment by antalvdb** [comment]
> > Opgesplitst in 5 regels:
> > > gaat V 0 0 0/te1
> > > gaat V 0 te2+Ia 0/te2
> > > gaat V 0 te3+Ia 0/te2I
> > > gaat V 0 te3+Ia 0/te3
> > > gaat V 0 te3+Ia 0
> > >
> > > In de derde variant zit de tegenspraak
> > > Welke kan er weg???
> >
> > de gaat V 0 te3+Ia 0/te2I regel klopt niet; zo’n te2I code staat voor
> > de ‘inverse’ gevallen waar het persoonlijk voornaamwoord na het
> > werkwoord staat, zonder -t. Dus “ga je”. Bovendien: te3 en te2 zouden
> > niet samen moeten voorkomen. Dit komt van een foute analyse af misschien.
> 
> Dit leidt tot de volgende 5 analyses:
> gaat==> [ [gaat]V te1 ]V V
> gaat==> [ [ga]V [t]te2 te2 ]V V
> gaat==> [ [ga]V [t]te3 te2I ]V V
> gaat==> [ [ga]V [t]te3 te3 ]V V
> gaat==> [ [ga]V [t]te3 ]V V
> 
> Die derde kan dus weg.
> Maar in de 2-de en 4-de zit, lijk mij redundante informatie, die in de
> 5-de dan weer niet zit.

Ja; ‘te2 te2’ is redundant - zou ‘te2’ moeten zijn. Zelfde voor ‘te3 te3’ en alle duplicaties van inflectionele tags.

> > Het is misschien interessant om eens te zoeken op te2I in CELEX en te
> > zien of er inconsistenties zijn te vinden.
> Er zijn bijna 600 entries in mbma-merged waarbij het woord eindigt op
> een 't' en die te2I hebben
> zo op het oog is het alleen bij 'gaat’ fout

OK, want er zijn uiteraard ook werkwoordsstammen die op -t eindigen (bijt, smijt, laat, …)

> > De “0/“ in alle codes is eigenlijk niet correct, want het is wel
> > degelijk de t die in z’n eentje een inflectie is. Eigenlijk zou er
> > moeten staan
> 
> Wat? ??
> Dit werkt:
> gaat V 0 0 0/te1
> gaat V 0 te2+Ia 0
> gaat V 0 te3+Ia 0
> 
> resultaat:
> gaat==> [ [gaat]V te1 ]V V
> gaat==> [ [ga]V [t]te2 ]V V
> gaat==> [ [ga]V [t]te3 ]V V
> 
> Maar dit wekt ook:
> gaat V 0 0 0/te1
> gaat V 0 0+Ia te2
> gaat V 0 0+Ia te3
> 
> geeft hetzelfde:
> gaat==> [ [gaat]V te1 ]V V
> gaat==> [ [ga]V [t]te2 ]V V
> gaat==> [ [ga]V [t]te3 ]V V
> 
> Net als:
> gaat V 0 0 0/te1
> gaat V 0+Ia 0 te2
> gaat V 0+Ia 0 te3
> 
> Wat is conceptueel beter? Inflecties zoveel mogelijk achteraan lijkt me
> het meest logisch
> De laatste oplossing dus?

(1) specifiek voor ‘gaat V 0 0 0/te1’ - net als de te2I vorm kan dit niet (“*ik gaat”). Dus de te1 vorm van gaat is niet correct en moet uit de trainingdata.

(2) wat bedoel je met de laatste oplossing? Deze?

gaat V 0 0+Ia te2
gaat V 0 0+Ia te3

Als ik in mbma-merged kijk naar andere werkwoorden dan is het niet anders:

boekt V 0 0 0 te2|te3

Het is met ‘ga’ alleen zo dat er nog een ‘a’ weggehaald moet worden voor de ’t’.

  Antal

--
Antal van den Bosch http://antalvandenbosch.ruhosting.nl
Center for Language Studies, Radboud University

**Comment by kosloot** [comment]
On 12/23/2016 02:46 PM, Antal van den Bosch wrote:
> > Die derde kan dus weg.
> > Maar in de 2-de en 4-de zit, lijk mij redundante informatie, die in de
> > 5-de dan weer niet zit.
>
> Ja; ‘te2 te2’ is redundant - zou ‘te2’ moeten zijn. Zelfde voor ‘te3
> te3’ en alle duplicaties van inflectionele tags.
>

Voor 'gaat' hebben we die nu ontdekt. In zijn algemeenheid is dat nog
best lastig...

> > > Het is misschien interessant om eens te zoeken op te2I in CELEX en te
> > > zien of er inconsistenties zijn te vinden.
> > Er zijn bijna 600 entries in mbma-merged waarbij het woord eindigt op
> > een 't' en die te2I hebben
> > zo op het oog is het alleen bij 'gaat’ fout
>
> OK, want er zijn uiteraard ook werkwoordsstammen die op -t eindigen
> (bijt, smijt, laat, …)
>
Ja, dat is het probleem. Maar een snelle blik levert geen andere fouten op.

> > > De “0/“ in alle codes is eigenlijk niet correct, want het is wel
> > > degelijk de t die in z’n eentje een inflectie is. Eigenlijk zou er
> > > moeten staan
> >
> > Wat? ??
..
> > De laatste oplossing dus?
>
> (1) specifiek voor ‘gaat V 0 0 0/te1’ - net als de te2I vorm kan dit
> niet (“*ik gaat”). Dus de te1 vorm van gaat is niet correct en moet
> uit de trainingdata.
>

Hmm, ook dat nog :)

> (2) wat bedoel je met de laatste oplossing? Deze?
>
> gaat V 0 0+Ia te2
> gaat V 0 0+Ia te3
>
Ja, inderdaad. Die andere variant had ik later nog bijgevoegd
> Als ik in mbma-merged kijk naar andere werkwoorden dan is het niet
> anders:
>
> boekt V 0 0 0 te2|te3
>
> Het is met ‘ga’ alleen zo dat er nog een ‘a’ weggehaald moet worden
> voor de ’t’.
>
Dan zijn we het eens...

Ko

**Comment by kosloot** [comment]
In ieder geval voor alle varianten met 'gaat' (139 zijn dat er) is dit nu uniform opgelost
