### ISSUE TITLE
frog server parses both headers and data when called with curl/wget

### ISSUE THREAD

**Issue by matjemeisje** [LanguageMachines/frog#28]
System: Linux Mint 18.1 (kernel: 4.4.0-53-generic)
curl version: 7.47.0
frog version: 0.13.8

Command entered:

`curl -H "User-Agent:" -H "Accept:" -H "Content-Length:" -H "Content-Type:" -H "Host:" -d "Dit is een test.`
`EOT`
`" localhost:8001`

Trace:

`== Info: Rebuilt URL to: localhost:8001/`
`== Info:   Trying 127.0.0.1...`
`== Info: Connected to localhost (127.0.0.1) port 8001 (#0)`
`=> Send header, 19 bytes (0x13)`
`0000: 50 4f 53 54 20 2f 20 48 54 54 50 2f 31 2e 31 0d POST / HTTP/1.1.`
`0010: 0a 0d 0a                                        ...`
`=> Send data, 21 bytes (0x15)`
`0000: 44 69 74 20 69 73 20 65 65 6e 20 74 65 73 74 2e Dit is een test.`
`0010: 0a 45 4f 54 0a                                  .EOT.`
`== Info: upload completely sent off: 21 out of 21 bytes`
`<= Recv data, 62 bytes (0x3e)`
`0000: 31 09 50 4f 53 54 09 50 4f 53 54 09 5b 50 4f 53 1.POST.POST.[POS`
`0010: 54 5d 09 53 50 45 43 28 64 65 65 6c 65 69 67 65 T].SPEC(deeleige`
`0020: 6e 29 09 31 2e 30 30 30 30 30 30 09 42 2d 50 45 n).1.000000.B-PE`
`0030: 52 09 42 2d 4e 50 09 30 09 52 4f 4f 54 0a       R.B-NP.0.ROOT.`
`<= Recv data, 482 bytes (0x1e2)`
`0000: 32 09 2f 09 2f 09 5b 2f 5d 09 4c 45 54 28 29 09 2././.[/].LET().`
`0010: 31 2e 30 30 30 30 30 30 09 4f 09 49 2d 4e 50 09 1.000000.O.I-NP.`
`0020: 31 09 70 75 6e 63 74 0a 33 09 48 54 54 50 09 48 1.punct.3.HTTP.H`
`0030: 54 54 50 09 5b 48 54 54 50 5d 09 53 50 45 43 28 TTP.[HTTP].SPEC(`
`0040: 64 65 65 6c 65 69 67 65 6e 29 09 31 2e 30 30 30 deeleigen).1.000`
`0050: 30 30 30 09 42 2d 4f 52 47 09 49 2d 4e 50 09 31 000.B-ORG.I-NP.1`
`0060: 09 6d 6f 64 0a 34 09 2f 09 2f 09 5b 2f 5d 09 4c .mod.4././.[/].L`
`0070: 45 54 28 29 09 31 2e 30 30 30 30 30 30 09 4f 09 ET().1.000000.O.`
`0080: 4f 09 33 09 70 75 6e 63 74 0a 35 09 31 2e 31 09 O.3.punct.5.1.1.`
`0090: 31 2e 31 09 5b 31 2e 31 5d 09 53 50 45 43 28 73 1.1.[1.1].SPEC(s`
`00a0: 79 6d 62 29 09 31 2e 30 30 30 30 30 30 09 4f 09 ymb).1.000000.O.`
`00b0: 42 2d 4e 50 09 33 09 6d 6f 64 0a 0a 31 09 44 69 B-NP.3.mod..1.Di`
`00c0: 74 09 64 69 74 09 5b 64 69 74 5d 09 56 4e 57 28 t.dit.[dit].VNW(`
`00d0: 61 61 6e 77 2c 70 72 6f 6e 2c 73 74 61 6e 2c 76 aanw,pron,stan,v`
`00e0: 6f 6c 2c 33 6f 2c 65 76 29 09 30 2e 37 37 37 30 ol,3o,ev).0.7770`
`00f0: 38 35 09 4f 09 42 2d 4e 50 09 32 09 73 75 0a 32 85.O.B-NP.2.su.2`
`0100: 09 69 73 09 7a 69 6a 6e 09 5b 7a 69 6a 6e 5d 09 .is.zijn.[zijn].`
`0110: 57 57 28 70 76 2c 74 67 77 2c 65 76 29 09 30 2e WW(pv,tgw,ev).0.`
`0120: 39 39 39 38 39 31 09 4f 09 42 2d 56 50 09 30 09 999891.O.B-VP.0.`
`0130: 52 4f 4f 54 0a 33 09 65 65 6e 09 65 65 6e 09 5b ROOT.3.een.een.[`
`0140: 65 65 6e 5d 09 4c 49 44 28 6f 6e 62 65 70 2c 73 een].LID(onbep,s`
`0150: 74 61 6e 2c 61 67 72 29 09 30 2e 39 39 39 31 31 tan,agr).0.99911`
`0160: 33 09 4f 09 42 2d 4e 50 09 34 09 64 65 74 0a 34 3.O.B-NP.4.det.4`
`0170: 09 74 65 73 74 09 74 65 73 74 09 5b 74 65 73 74 .test.test.[test`
`0180: 5d 09 4e 28 73 6f 6f 72 74 2c 65 76 2c 62 61 73 ].N(soort,ev,bas`
`0190: 69 73 2c 7a 69 6a 64 2c 73 74 61 6e 29 09 30 2e is,zijd,stan).0.`
`01a0: 39 30 33 30 35 35 09 4f 09 49 2d 4e 50 09 32 09 903055.O.I-NP.2.`
`01b0: 70 72 65 64 63 0a 35 09 2e 09 2e 09 5b 2e 5d 09 predc.5.....[.].`
`01c0: 4c 45 54 28 29 09 31 2e 30 30 30 30 30 30 09 4f LET().1.000000.O`
`01d0: 09 4f 09 34 09 70 75 6e 63 74 0a 0a 52 45 41 44 .O.4.punct..READ`
`01e0: 59 0a                                           Y.`

**Comment by proycon** [comment]
Ah, no I see what you meant earlier. This is simply because the Frog server is not an HTTP server :) Just send "Dit is een test.\nEOT\n".

**Comment by kosloot** [comment]
Frog offers just a simple TCP server.
See the manual on: https://languagemachines.github.io/frog/
chapter 4.1.2

As a side note: 
Maybe HTTP version and/or JSON-like output is an option?

**Comment by matjemeisje** [comment]
Ah, ok. :)
