### ISSUE TITLE
Money, Percent, Date, and Time Named entity types in Frog

### ISSUE THREAD

**Issue by emehdad** [LanguageMachines/frog#29]
Stanford NER has a 7 class model which includes Location, Person, Organization, Money, Percent, Date, Time. I cannot find this in frog documentation. Is it easy to add this feature?

**Comment by kosloot** [comment]
the NER module is briefly described in the frog documentation.
Available from [here](https://languagemachines.github.io/frog/) chapter 5.2.7
It refers to this documentation:
Desmet, B. and V. Hoste. 2009. Named Entity Annotatierichtlijnen voor het Nederlands. Technical Report LT3
09.01., LT3, University Ghent, Belgium.

It is in Dutch, but so is Frog :)

But to summarize: The NER tags assigned by Frog are:
EVE, ORG, PER, PRO, LOC, MISC
So no money is involved :0

Training a new NER is possible, but assumes a lot of tagged Dutch data and some knowledge about training our Memory Based Tagger. [MBT](https://languagemachines.github.io/mbt/)

**Comment by kosloot** [comment]
Closing, because we don't have resources, nor the need to improve the NER
