### ISSUE TITLE
xml output support for FrogAPI::Frogtostring

### ISSUE THREAD

**Issue by jelmervdl** [LanguageMachines/frog#33]
Python-frog, the python bindings for Frog provide an option to return a FoLiA document when you set the xmlout parameter to true. However, the method [that the python bindings call](https://github.com/proycon/python-frog/blob/master/frog_wrapper.pyx#L152), [FrogAPI::Frogtostring](https://github.com/LanguageMachines/frog/blob/master/src/FrogAPI.cxx#L1193), does not take this option (doXMLout?) into account.

**Comment by kosloot** [comment]
Well, the [FrogAPI::Frogtostring](https://github.com/LanguageMachines/frog/blob/master/src/FrogAPI.cxx#L1193) method creates a FoLiA Document, and then returns the serialized version.

Is it your intention to get a pointer to the underlying Document? Normally that is unwise.
What is your use-case? Maybe @proycon could add a Python method. But then you still need to use the  libfolia C++ API  to process it..

**Comment by jelmervdl** [comment]
Python-frog's [Frog::process](https://github.com/proycon/python-frog/blob/master/frog_wrapper.pyx#L176) seems to implement code to return [a python-version of the document](https://github.com/proycon/python-frog/blob/master/frog_wrapper.pyx#L24).

The document in the line `return PynlplFoliaDocument(string=self.process_raw(text))` expects `string` to be XML, but Frog::Frogtostring, which is eventually called via the process_raw call, can only return the results via [FrogAPI::showResults](https://github.com/jelmervdl/frog/blob/master/src/FrogAPI.cxx#L1086):
```
stringstream ss;
FrogDoc( *doc, true );
showResults( ss, *doc );
delete doc;
return ss.str();
```

If the Frog::Frogtostring method could return XML as a string instead of the tab delimited output when doXMLout is true, I think the code that is already present in the python wrapper will work. The code to switch between xml and tabs is already present in Frog::Frogserver:
```
if ( options.doXMLout ){
  doc.save( outputstream, options.doKanon );
}
else {
  showResults( outputstream, doc );
}
```

A simple example of what I tried to do:
```
import frog
from pynlpl.formats import folia

doc = folia.Document(file="in_folia.xml")
handle = frog.Frog(frog.FrogOptions(xmlin=True,xmlout=True,parser=False,morph=False,lemma=False,ner=False))
output = handle.process(doc)
```

I expect output to be a folia.Document, but currently this throws an exception because the PynlplFoliaDocument ([created in process](https://github.com/proycon/python-frog/blob/master/frog_wrapper.pyx#L185)) expected XML but got tabs instead.

(I was trying to setup a build environment to make a pull request, because it seems really simple to implement 😄 )

**Comment by kosloot** [comment]
A, OK. Now i see. Indeed not a serialized Document but a tabbed version  is returned. :{
Hmm. I leave it to @proycon to solve this. :)

**Comment by kosloot** [comment]
Ok,
in git the code for  [FrogAPI::Frogtostring](https://github.com/LanguageMachines/frog/blob/master/src/FrogAPI.cxx#L1193) is changed now.
The example should work as expected.

**Comment by jelmervdl** [comment]
Thanks!

I've tested it and the example indeed now works as expected.
