### ISSUE TITLE
Implement textclass attribute support

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/frog#36]
*Feature request:* Add a textclass attribute (proycon/folia#29) to all added annotations when ``--textclass != "current"``

**Comment by kosloot** [comment]
ok, for cases like POS and Lemma this is straightforward:
            \<pos class="VG(neven)" confidence="0.992995" head="VG" textclass="OCR"\>
                 \<feat class="neven" subset="conjtype"/\>
            \</pos\>
  
and:
 \<lemma class="en"/\>
But how about entity layers (Named Enttites, Chunking)
Doe we need testclass at every level? Or only at the layer?

**Comment by kosloot** [comment]
ok. on the chunks and the entities

**Comment by kosloot** [comment]
Implemented this feature.
