### ISSUE TITLE
Frog sometimes segfaults when processing large batches

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/frog#39]
When processing large batches of FoLiA input and FoLiA output (though possibly also plain text input), Frog sometimes crashes with a segfault in a non-reproducible fashion. Thread safety issues seem to be the most likely suspect.

**Comment by kosloot** [comment]
well, I don't think this is solved completely. Some extra Thread synchronizing is added.
And nobody complains anymore...
Closing for now
