### ISSUE TITLE
Release frog 0.13.8?

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/frog#40]
Similar to LanguageMachines/ucto#33: Last release was in January and there has been considerable work since (over 100 commits). Normal LaMachine users will still not benefit from all of this yet until release. I recommend releasing as soon as the version is deemed stable. (along with frogdata, after libfolia for folia 1.5)

**Comment by kosloot** [comment]
release will be postponed until new Chunker is incorporated (requires new FrogData too) RSN?
a new NER is already available. (with new Frogdata)
