### ISSUE TITLE
Move Frog documentation sources to this git repo

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/frog#48]
They are still on overleaf; best keep everything together with the sources (so versions correspond to the source code).

Also: fix python-frog error in documentation, explicit configuration file path is outdated and needs to be removed

**Comment by kosloot** [comment]
The TEX files have been moved to the frog repo now (in /docs/texfiles )
compilation with 'latex' fails, bu with 'pdflatex' it works.

**Comment by proycon** [comment]
Great, perhaps we should delete the project on overleaf now to prevent diverging edits.

**Comment by kosloot** [comment]
@Irishx is to be consulted then.
