### ISSUE TITLE
Perfomance and accuracy on tweets

### ISSUE THREAD

**Issue by barthr** [LanguageMachines/frog#50]
I'm trying to real time process dutch tweets for domain specific named entity recognition. I build a ner system but struggling with finding a correct dependency parser, pos tagger. The core requirement is perfomance, do you think frog is suitable for this or should I look further to something like alpino.

**Comment by proycon** [comment]
For dependency parsing Alpino has better accuracy, but it is far slower than Frog, so Frog is probably the way to go here yes.

**Comment by proycon** [comment]
By the way, I see you like Go, so you might want to check out https://github.com/Machiel/gorf (not ours though)

**Comment by barthr** [comment]
Thanks!
