### ISSUE TITLE
Parse CGN subsets and classes from FoLiA set definition

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/frog#51]
Currently  ``CGNTagger::fillSubSetTable()`` is hard-coded. Ideally it should be derived from a folia set definition (in the new RDF turtle notation, e.g. https://github.com/proycon/folia/blob/master/setdefinitions/frog-mbpos-cgn).

Context: I'm currently running into some *unable to find cgn subset for class* errors as I'm working with an extended version of CGN (by INT) which our current mapping does not completely cover (trainde a new model with ``froggen``. I'm contemplating whether to just hack in the extension for the time being ...

**Comment by kosloot** [comment]
Frog now reads two files containing the subsets and the constraints.
This are very simple files. They should be generated from the FoLiA set definitions or such.

**Comment by kosloot** [comment]
I assume this works, and the only improvement left is have some function to directly read the 'yet to be defined' XML representation of sets and constraints
