### ISSUE TITLE
Redesign Frog

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/frog#54]
@antalvdb and @proycon 

I think it is time for a great overhaul of Frog, to 
- reduce complexity
- increase maintainability
- be more flexible
- speed things up

The main aspect to consider:
At the moment Frog uses FoLiA as it's internal data-structure. That seemed a good plan once, but with growing data-sets this now became a memory hog. Also it has some nasty MultiThreading issues. (like different FoLiA files after every run, all valid)
It also makes processing line-by-line almost impossible, as the whole input file is stuffed into one FoLiA document.
I think that processing smaller chunks would speed up the process, and will deliver output at a more constant pace. (not just one burst of FoLiA at the end)
This would mean that we cannot directly use the Ucto 'tokenize-to-FoLiA` facility anymore. But that is a small burden, IMHO.
Also there remains the problem of FoLiA output at the end of Frog. That would still mean a very large file, on large input. 
But it IS possible to create a 'main' file with a bunch of sub-files, using the FoLiA 'external' mechanism. In the current situation this is almost impossible.

Also I am working on a FoLiA Builder class, which creates a FoLiA file on disk incrementally, without first creating it completely in memory. This reduces the footprint of Frog but still may produce insane large files (>10Gb or so)

caveat:
This solution **does not** work for FoLiA input into Frog. If you read a very large file,it stays large :)
What MIGHT be possible is to do is to make a FoLiA Reader class, which reads chunks form a FoLiA file, have them processed by Frog and assemble the results back into another FoLiA file. (using the Builder for instance)

I think other improvements might also be welcome, but this is the most intrusive one, I guess.
At the and, the Frog results will not be changed, just produced faster.

I think I would need a few months to accomplish this. It would be a nice task. But a bit to large to do 'on the side'
maybe a CLARIAH+ or a CLARIN-NL project?

Comments and additions welcome!

**Comment by proycon** [comment]
I agree with this plan, it sounds like a very good idea. The performance is often a bottleneck nowadays, so improvement here with more streaming solutions would benefit a lot of future work. I suppose such as project would also lead to reusable improvements in libfolia and possibly ucto, so have a wider impact.

I hope it fits in CLARIAH+?

**Comment by proycon** [comment]
I also support the idea of a steaming FoLiA Reader class to deal with FoLiA input, it does sound feasible.

**Comment by kosloot** [comment]
as @antalvdb I added @Irishx to the discussion

**Comment by kosloot** [comment]
Indeed redesigning Frog implies adding new (nice) features to libfolia and ucto.

**Comment by antalvdb** [comment]
I also agree with Ko - the route to build both a piece-by-piece Builder and Reader sounds like a good plan.

CLARIAH-PLUS: yes, good point - could actually be work for WP6, rather than for WP3. To be continued (and I guess project politics do not belong on GitHub ;-))

  Antal

--
On 5 Jul 2018, at 11:15, Maarten van Gompel <notifications@github.com<mailto:notifications@github.com>> wrote:


I agree with this plan, it sounds like a very good idea. The performance is often a bottleneck nowadays, so improvement here with more streaming solutions would benefit a lot of future work. I suppose such as project would also lead to reusable improvements in libfolia and possibly ucto, so have a wider impact.

I hope it fits in CLARIAH+?

**Comment by kosloot** [comment]
One other major issue is making Frog work on multi-token words. (not being MWU's)
Some parts (line MBLEM) don't have real restrictions, but others do. Mbt being the hard one probably.
Also ucto  is completely based on the idea that white-space separates tokens and is insignificant.
This is really troublesome.  Clever solutions welcome.

Examples of constructions we should be able to handle:
``om⊔dat	omdat	VG(onder,zonder)``
(2 words, 1 lemma, 1 POS tag)
``tfierendeel	dat⊕vierdedeel	LID(bep,zonder)⊕N(soort,ev,zonder)``
(1 word, 2 lemma, 2 pos tags)

**Comment by kosloot** [comment]
So this work is partly done: Frog can handle FoLiA sentence-per-sentence using the new folia::processor() class. This speeds up a bit and diminishes memory usage.
Other developments like running NER ans IOB with the outcome of the Tagger as enrichments did slow down the whole process. So the netto effect is minimal.
