### ISSUE TITLE
Ability to control logging/output

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/frog#55]
Forwarded from proycon/python-frog#9, by @gmjonker

**Comment by kosloot** [comment]
@gmjonker wrote:

When processing large corpora, frog produces a lot of output like this:

20180711:191754:590:Wed Jul 11 19:17:54 2018 process 2 sentences
20180711:191754:592:Wed Jul 11 19:17:54 2018 done with sentence[1]
20180711:191754:607:Wed Jul 11 19:17:54 2018 done with sentence[2]

This drowns out other logging, like progress information.

It would be nice if the frog output/log level could be controlled.

**Comment by kosloot** [comment]
Yeah. you are right. his should be a bit configurable. It is always a point of discussion what and why to output.
The ``done with sentence[1]`` lines were added recently because of complaints about seeing no progress. :)

good suggestions about output levels would be nice.

**Comment by gmjonker** [comment]
For me, being able to suppress the lines mentioned above would be ideal.

Maybe a silent mode that only outputs errors?

**Comment by kosloot** [comment]
well, you could always redirect stdout to a file, and watch only stderr.

**Comment by gmjonker** [comment]
I'm using `python-frog` in PyCharm, which doesn't allow me to watch only stdout and not stderr, or redirect them. 
Also, it seems that all the logging comes in on stderr, which I do want to see of course...

**Comment by kosloot** [comment]
yes. you are right.
Anyway. Not something I can change instantly in Frog. Let alone the Python layers...

**Comment by proycon** [comment]
Perhaps some kind of ``--verbosity`` flag with an integer value would be a good solution? Once we have that it's easy to add to ``python-frog``.

**Comment by kosloot** [comment]
yeah, that's the plan. Discussion will start about what to include at what level...

And an implementation 'detail': 
Because of the multi-threading of Frog, a single Logfile with guards is used. Which is tied to stderr. We would need 2 of those then, one to stderr, and one to stdout.

**Comment by kosloot** [comment]
one other design choice that will haunt us:
Default Frog writes is 'tabbed' output to stdout. That's why ALL other output is send to stderr.
Introducing verbosity levels would still mean writing to stderr, until we decide to make the -o output option obligatory.

A more easy path might be using the -d option, with value 0 to be (almost) silent. value 1 some useful info, and levels above for 'real' debugging.

**Comment by gmjonker** [comment]
I think writing diagnostic information to `stderr` is fine.

So +1 for the `--verbosity`/`-d` option.

**Comment by kosloot** [comment]
Well, as a quick hack, I made the `-d1` option much less verbose, so it is in fact a verbosity option now.
the default is `-d0` and even more silent.
Maybe more output could be hidden for `-d0`
after my holidays then...

**Comment by kosloot** [comment]
Already many moons ago, i added a separate debug file to Frog. When -d or --debug is used a debug file frog.\<random_number\>.debug is created where debug info is stored.
Normal cout output is quite minimal now.
