### ISSUE TITLE
Tokenizer very slow on long sequence of numbers

### ISSUE THREAD

**Issue by gmjonker** [LanguageMachines/frog#56]
Frogs tokenizer becomes very slow when processing a sentence like 

    Ik zie dat op dit moment het oude simkaartnummer  8931443451404568470  nog actief is.

    frog-:tokenisation took:  145 seconds, 5 milliseconds and 633 microseconds

Some tests:

89314434514045684 -> frog-:tokenisation took:  13 seconds, 872 milliseconds and 555 microseconds
893144345140456847 -> frog-:tokenisation took:  71 seconds, 461 milliseconds and 571 microseconds
8931443451404568470 -> frog-:tokenisation took:  145 seconds, 5 milliseconds and 633 microseconds
89314434514045684701 -> frog-:tokenisation took:  354 seconds, 345 milliseconds and 932 microseconds

Tested on MacOS

**Comment by kosloot** [comment]
OK, this was a known problem with long numbers. But is hat is fixed in the 0.7 release of uctodata on may 16 2018
Which version of uctodata do you use?

I can tokenize 
``'Ik zie dat op dit moment het oude simkaartnummer  89314434514045684701010103872132183848438143821  nog actief is.'``
within a few milliseconds.

**Comment by gmjonker** [comment]
```sh
$ frog -V
frog 0.14 (c) CLTS, ILK 1998 - 2018
CLST  - Centre for Language and Speech Technology,Radboud University
ILK   - Induction of Linguistic Knowledge Research Group,Tilburg University
based on [ucto 0.12, libfolia 1.12, timbl 6.4.11, ticcutils 0.18, mbt 3.3.1]
```

**Comment by kosloot** [comment]
OK, unfortunately no information about the uctodata version. But: none of these are the most recent stable releases. 
So I suggest to upgrade. 
If that is a problem, upgrading only uctodata might do the trick.

**Comment by kosloot** [comment]
assume this is sufficiently answered
