### ISSUE TITLE
--threads does not combine with -S (server mode). Feature or bug?

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/frog#6]
I noticed this when starting frog for tscan (the script failed). I assume this is intended behaviour and not a bug?

**Comment by kosloot** [comment]
This is intended behaviour, implemented by Maarten van Gompel:
`commit a9f665eb66fa35e194d4d4f9de82703c1e7dd5c8
Author: mvgompel <mvgompel@12f355fe-0486-481a-ad91-c297ab22b4e3>
Date:   Wed Jan 11 14:23:26 2012 +0000

    No parallelisation in server mode (would fork on each snippet, too expensive
)
    
`

**Comment by kosloot** [comment]
note:
What does ''the script failed" exactly mean?
running just "frog -threads=6 -S 2050" works for me

**Comment by kosloot** [comment]
AHA
is appears that you get a message:
"frog-:unhandled commandline options: --threads=8"
in the situation that OpenMP support is not enabled.
This message is correct as such. But maybe a bit vague.

**Comment by kosloot** [comment]
Added a clearer message
