### ISSUE TITLE
[question] Which datasets are used for training each specific module

### ISSUE THREAD

**Issue by olix20** [LanguageMachines/frog#63]
Hi and thanks for the great work! 

Can i check if there's a documentation on what datasets were used for training each specific module of Frog (eg. pos tagger/dependency parser)? 

Specifically I'd like to know if Frog is suitable for spoken language and if CGN annotations were used for training.

**Comment by kosloot** [comment]
Assuming this is not relevant anymore. (sorry for ignoring it)

**Comment by proycon** [comment]
Let's at least point to the documentation for completion's sake, this section should answer some of those questions: https://frognlp.readthedocs.io/en/latest/advanced.html
