### ISSUE TITLE
Outdated icu version

### ISSUE THREAD

**Issue by cdfa** [LanguageMachines/frog#69]
I got the following error when trying `from frog import Frog, FrogOptions` after updating `icu ` to 64.1: `ImportError: libicuio.so.63: cannot open shared object file: No such file or directory`.

Installing [icu63](https://aur.archlinux.org/packages/icu63/) from the AUR (and updating it's `icu` source to resolve the missing ssl certificate). Fixed the problem.

Being able to run with the latest `icu` would be nice.

**Comment by kosloot** [comment]
I assume we are talking Python here?
So this is a python-frog problem then.

**Comment by cdfa** [comment]
Ah, my apologies. I didn't know there was a python specific repo. I'll report there.
