### ISSUE TITLE
No use of language detection when handling pretokenised FoLiA

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/frog#73]
Continuation of #72, I have a pretokenised FoliA file with language tags, but they seem to be ignored in Frog now, meaning 

Input: https://lst.science.ru.nl/~proycon/issue73_a.xml

Command: ``frog --language=nld --skip=tmcpna HuygensING-brieven-correspondenten issue73_a.xml -X test.xml``

The problem occurs both with and without the tokeniser.

**Comment by proycon** [comment]
The first paragraph (one word), is marked as Latin and should therefore not be Pos-tagged/lemmatised.

**Comment by kosloot** [comment]
fixed
