### ISSUE TITLE
Misinterpretation of columns when morph and/or daringmorph are disabled

### ISSUE THREAD

**Issue by fkunneman** [LanguageMachines/frog#74]
Disabling morph and daringmorph through pythonfrog leads to a columninput to frog that is misinterpreted. Concretely, the tag is interpreted as a float, leading to a "ValueError: could not convert string to float: 'N(eigen,zonder)'" in python.

**Comment by kosloot** [comment]
I checked in a fix (devleopment branch) . Please test

**Comment by fkunneman** [comment]
Tested to satisfaction.
