### ISSUE TITLE
Frog python binding breaks because Frog no longer outputs FoLiA XML to stream with doXMLout and without output XML filename

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/frog#75]
Execution path: ``Frogtostring -> FrogFile -> run_text_engine``

Probably needs extra logic checking ``doXMLout`` (and possibly an extra output stream if you don't want to reuse os?) here: 
https://github.com/LanguageMachines/frog/blob/master/src/FrogAPI.cxx#L1694

**Comment by kosloot** [comment]
because of the 6 possible execution paths, solving this is not easy.
It seems wise to sort this out better an create a sustainable solution.
Keep this on hold for a month or so....
If desired a workaround is possible in calling FrogFile directly WITH an xml output filename
