### ISSUE TITLE
segmentation fault with xmldir after no result?

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/frog#76]
This is a weird segmentation fault issue which I haven't fully identified yet, but want to record here for future reference:

```  frog-:Fri Jun 21 20:40:35 2019 Frogging input/HuygensING-epistolarium-1-1_b1f159df-baef-401a-a4a0-20abc6635633.folia.xml
  frog-:document contains no text in the desired inputclass: current
  frog-:NO result!
  frog-:tokenisation took:  0 seconds, 0 milliseconds and 0 microseconds
  frog-:CGN tagging took:   0 seconds, 0 milliseconds and 0 microseconds
  frog-:Mblem took:         0 seconds, 0 milliseconds and 0 microseconds
  frog-:Frogging in total took: 0 seconds, 0 milliseconds and 0 microseconds
  frog-:Fri Jun 21 20:40:36 2019 Frogging input/HuygensING-epistolarium-1-1_b22f3427-668b-4ded-9024-a2ebe5726731.folia.xml
  .command.sh: line 24: 32410 Segmentation fault      frog $opts --override tokenizer.rulesFile=tokconfig-nld-historical --xmldir "." --nostdout --testdir input/ -x
```

I haven't been able to easily reproduce it yet and it seems to only occur with the xmldir option and only when the **previous** file does not contain any text: 

```
  frog-:document contains no text in the desired inputclass: current
  frog-:NO result!
```

**Comment by proycon** [comment]
If I remove the "no result" files from the directory, everything processes fine.

**Comment by kosloot** [comment]
Today I stumbled upon the same problem an was able to create a test-case which most of the times failed. It appeared that frog, when running on multiple files, in rare occasions reused a document which was rejected earlier on.
This should be fixed now.

**Comment by kosloot** [comment]
This problem magicly  reappeared somehow

**Comment by kosloot** [comment]
was caused by recent change in ucto, fixed again
