### ISSUE TITLE
Server mode creates only 1 paragraph

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/frog#84]
As signaled by @joepfranssen in https://github.com/proycon/tscan/issues/14:

When the Frog server is fed 2 or more lines, separated by a blank lines, NO extra paragraphs are created.

This seems a regression from the old behaviour. The command-line version DOES work as expected.

**Comment by kosloot** [comment]
solved in Ucto

**Comment by joepfranssen** [comment]
Thanks! Seems to work perfectly :) Thanks for the fast solution
