### ISSUE TITLE
Add JSON output as an alternative to 'tabbed' format

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/frog#85]
The 'tabbed' format is quite rigid, and sometimes difficult to read. (especially when some modules are skipped). 
It might be handy to create JSON output as an alternative. This might really be useful for the SERVER mode.

NOTE: consider JSON input for the server too then,

**Comment by proycon** [comment]
This would indeed also be useful for the python-frog binding... more robust parsing..

**Comment by kosloot** [comment]
A first attempt is in GIT now. Needs some testing.

**Comment by kosloot** [comment]
nobody complained about the JSON
