### ISSUE TITLE
Bug: frog server; frog-:connection lost unexpected : write to client failed

### ISSUE THREAD

**Issue by devbeoservice** [LanguageMachines/frog#95]
Requests made to frog server are failing

Ubuntu 20.04
Compiled version of frog
python3-pynlpl (debian/ubuntu package) 

frog-:connection lost unexpected : write to client failed

**Comment by devbeoservice** [comment]
Looks like it actually works alright. I don't know why it gives the error message server-side, client side processed sentences arrive.

**Comment by kosloot** [comment]
I assume the server just notices that the client disappeared, after receiving what it requested.
