### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/frog#97]
@kosloot  There have been some improvements to Frog and the stack below it recently, how ready are we for a new release?

**Comment by kosloot** [comment]
Well, I planed a major update to Timbl "real soon now". (days, not weeks)
When that is done, releases of everything else are indeed wise to do.
Frog is a bit special, as I am still working on a major refactoring in the background, but that is not done yet.
So I think it is best to do an intermediate Frog release, without including the "deep" branch and leave that for a later moment.
One ramification being that the 'deep' branch changes the Frog API, which might imply some changes to other programs 
outside "our" stack. (most notably, or maybe just Tscan)

**Comment by proycon** [comment]
Ok, that sounds good! (including leaving the deep branch for later)

**Comment by kosloot** [comment]
frog v0.26 has been released just yet
