### ISSUE TITLE
[Docker] Initialization fails for nld-vnn and dum

### ISSUE THREAD

**Issue by tcbrouwer** [LanguageMachines/frog#99]
I run Frog from https://hub.docker.com/r/proycon/frog:latest . Currently running

```docker run proycon/frog --language=dum```

results in

```
frog-:config read from: /usr/local/share/frog/dum/frog.cfg
frog-:Missing [[mbma]] section in config file.
frog-:Disabled the Morhological analyzer.
frog-:Missing [[IOB]] section in config file.
frog-:Disabled the IOB Chunker.
frog-:Missing [[NER]] section in config file.
frog-:Disabled the NER.
frog-:Missing [[mwu]] section in config file.
frog-:Disabled the Multi Word Unit.
frog-:Also disabled the parser.
frog-mblem-:Initiating lemmatizer...
ucto: textcat configured from: /usr/local/share/ucto/textcat.cfg
frog-tok-:Language List =[dum]
ucto: No useful settingsfile(s) could be found (initiating from language list: [dum])
frog-tagger-tagger-:reading subsets from /usr/local/share/frog/dum//crmsub.cgn
frog-tagger-tagger-:reading constraints from /usr/local/share/frog/dum//crmconstraints.cgn
frog-:Initialization failed for: [tokenizer] 
frog-:fatal error: Frog init failed
```

Similar for nld-vnn (after mitigation https://github.com/LanguageMachines/frogdata/pull/7 )

With my previous build from 6 months ago, I did not encounter this initialization problem.

My current mitigation is to use

```docker run proycon/frog --language=dum,nld```

instead. With this the initialization succeeds, and if I understand correctly from

```
WARNING: you used the --language=dum,nld option with more then one language 
	 specified. These values will be handled to the tokenizer, but Frog
	 will only handle the first language: dum for further processing!
```

still only dum is used for Frog, which is the core of our use case.

As a sidenote, in general the dockerized deployment of Frog is very helpful to me.

**Comment by kosloot** [comment]
Wow. This seems a strange regression.

Ucto assumes the data to be in ``.../share/ucto/tokconfig-nld-historical``
But frog asks to look for ``.../share/ucto/tokconfig-nld-historical``

Running with ``frog --language=nld-historical`` is NOT working too, as frog expects a  nld-historical.cfg file then

Quick fix: (assuming you have enough rights to do so):
``ln -s /usr/local/share/ucto/tokconfig-nld-historical /usr/local/share/ucto/tokconfig-dum``

After that, frog will find the tokconfig-dum file.

Needs a more permanent solution.

**Comment by kosloot** [comment]
Another not-intrusive possibility is to start Frog using the ``-c`` or ``--config`` option:
``frog -c dum/frog.cfg``
This will find the correct tokenizer files.

But your report reveals some more general problem we need to investigate. 
1. When using a specified configuration file, like ``tokconfig-nld-historical`` the language detection using TextCat should be disabled!. TextCat has NO KNOWLEDGE about those languages, and wil not work correctly.
2.

**Comment by kosloot** [comment]
@tcbrouwer To clarify a few things:

the --languages option is used to initialize the ucto tokenizer with 1 or more language configurations.
When you use ``--languages=dum`` in Ucto, the tokenizer searches for a setting for ``dum`` and will fail to do so.
It cannot run, nor will frog.

When you use ``--languages=dum,nld`` in Ucto, the tokenizer wil NOT find a setting for ``dum`` but it wil find one for ``nld``.
Ucto, and therefore Frog will happily run with only the 'standard Dutch` tokenizer rules. NOT those for historical   dutch.
This is probably not what you wanted or expected. Failing to run would probably more informative.

But there is an oddity in using ``--language=dum`` IN Frog  as it CORRECTLY selects the .``../dum/*`` configuration files
In that file it should find the line: ``rulesFile=tokconfig-nld-historical``
And then pass ``nld-historical `` on to the Tokenizer.
But it fails doing so.  That is the real bug. We will address that.

There was also a problem that commandline ucto will clearly warn you when you use an 'unknown'  language, but when integrated in Frog, this message was redirected to a debug file. Not directly to the user.  This will be fixed too.

**Comment by kosloot** [comment]
assume this is a non-issue atm
